plugins {
    id 'java'
    alias(gradlePluginLibs.plugins.spring.boot)
}

dependencies {
    // Spring Boot
    implementation libs.spring.boot.starter.web
    developmentOnly libs.spring.boot.devtools

    // A12 Workflows
    implementation a12Libs.workflows.engine

    // Testing
    testImplementation testCatalogLibs.spring.boot.starter.test
    testImplementation testCatalogLibs.cibseven.junit5
    testImplementation testCatalogLibs.cibseven.bpm.assert
}

test {
    useJUnitPlatform()
}

springBoot {
    mainClass = 'com.mgmtp.a12.tutorial.workflow.engine.WorkflowEngineTutorialApplication'
}
