rootProject.name = 'a12-tutorial-application'

include 'client'
include 'compose'
include 'generate-gift-card-external-worker'
include 'server'
include 'server:app'
include 'server:init'
include 'import'
include 'workflow-engine'

dependencyResolutionManagement {
    def springBootVersion = '3.5.9'
    def cibsevenVersion = '2.0.0'
    versionCatalogs {
        gradlePluginLibs {
            version('spring-boot', springBootVersion)
            version('test-logger', '3.2.0')
            version('docker-compose', '0.17.6')
            version('docker-remote-api', '9.3.1')
            version('versions-update', '0.42.0')
            version('node-gradle', '7.0.1')
            version('sonarqube-scanner','6.0.1.5171')
            version('rewrite', '7.10.0')
            version('sbom', '2.4.1')

            plugin('spring-boot', 'org.springframework.boot').versionRef('spring-boot')
            plugin('test-logger', 'com.adarshr.test-logger').versionRef('test-logger')
            plugin('docker-compose', 'com.avast.gradle.docker-compose').versionRef('docker-compose')
            plugin('docker-remote-api', 'com.bmuschko.docker-remote-api').versionRef('docker-remote-api')
            plugin('versions-update', 'com.github.ben-manes.versions').versionRef('versions-update')
            plugin('node-gradle', 'com.github.node-gradle.node').versionRef('node-gradle')
            plugin('sonarqube', 'org.sonarqube').versionRef('sonarqube-scanner')
            plugin('rewrite', 'org.openrewrite.rewrite').versionRef('rewrite')
            plugin('sbom', 'org.cyclonedx.bom').versionRef('sbom')
        }

        a12Libs {
            version('base', '29.2.0')
            version('kernel', '30.7.1')
            version('uaa', '9.3.1')
            version('dataservices', '38.3.4')
            version('workflows', '12.2.1')

            library('uaa-authorization-a12-extension', 'com.mgmtp.a12.uaa', 'uaa-authorization-a12-extension').versionRef('uaa')
            library('uaa-authorization-introspector', 'com.mgmtp.a12.uaa', 'uaa-authorization-introspector').versionRef('uaa')
            library('dataservices-server-app', 'com.mgmtp.a12.dataservices', 'dataservices-server-app').versionRef('dataservices')
            library('dataservices-server-init-app', 'com.mgmtp.a12.dataservices', 'dataservices-server-init-app').versionRef('dataservices')
            library("dataservices-data-seed", "com.mgmtp.a12.dataservices", "dataservices-data-seed").versionRef("dataservices")
            library("workflows-extension", "com.mgmtp.a12.workflows", "workflows-extension").versionRef("workflows")
            library("workflows-engine", "com.mgmtp.a12.workflows", "workflows-engine-distribution").versionRef("workflows")

            library('base-bom', 'com.mgmtp.a12.base', 'base-bom').versionRef('base')
            library('kernel-bom', 'com.mgmtp.a12.kernel', 'kernel-bom').versionRef('kernel')
            library('uaa-bom', 'com.mgmtp.a12.uaa', 'uaa-bom').versionRef('uaa')
            library('dataservices-bom', 'com.mgmtp.a12.dataservices', 'dataservices-parent').versionRef('dataservices')
        }

        libs {
            version('spring-boot', springBootVersion)
            version('rewrite-static-analysis', '2.20.0')
            version('logstash','7.4')
            version('logback-classic','1.5.6')
            version('cibseven', cibsevenVersion)
            version('jaxb','4.0.1')

            library('cibseven-external-task-client', 'org.cibseven.bpm.springboot', 'cibseven-bpm-spring-boot-starter-external-task-client').versionRef('cibseven')
            library('jaxb-api', 'jakarta.xml.bind', 'jakarta.xml.bind-api').versionRef('jaxb')
            library('rewrite-static-analysis', 'org.openrewrite.recipe', 'rewrite-static-analysis').versionRef('rewrite-static-analysis')
            library('spring-boot-configuration-processor', 'org.springframework.boot', 'spring-boot-configuration-processor').versionRef('spring-boot')
            library('spring-boot-devtools', 'org.springframework.boot', 'spring-boot-devtools').versionRef('spring-boot')
            library('spring-boot-starter-mail', 'org.springframework.boot', 'spring-boot-starter-mail').versionRef('spring-boot')
            library('spring-boot-starter-web', 'org.springframework.boot', 'spring-boot-starter-web').versionRef('spring-boot')
            library('logstash', 'net.logstash.logback', 'logstash-logback-encoder').versionRef('logstash')
            library('logback-classic', 'ch.qos.logback', 'logback-classic').versionRef('logback-classic')
        }

        testCatalogLibs {
            version('cibseven', cibsevenVersion)
            version('spring-boot', springBootVersion)
            version('testcontainers', '1.19.8')

            library('spring-boot-starter-test', 'org.springframework.boot', 'spring-boot-starter-test').versionRef('spring-boot')
            library('testcontainers-junit5', 'org.testcontainers', 'junit-jupiter').versionRef('testcontainers')
            library('cibseven-junit5', 'org.cibseven.bpm', 'cibseven-bpm-junit5').versionRef('cibseven')
            library('cibseven-bpm-assert', 'org.cibseven.bpm', 'cibseven-bpm-assert').versionRef('cibseven')
        }
    }
}
