# Resources
mgmtp.a12.dataservices.initialization.import.models.path=file:../../import/models/

spring.datasources.dataservices.embedded-postgres.path=file:../postgres/ds-embedded-postgres
spring.datasources.contentstore.embedded-postgres.path=file:../postgres/cs-embedded-postgres
