# Resources
mgmtp.a12.dataservices.initialization.import.models.path=file:../../import/models/
# CONFIG: dataservices using h2 file
spring.datasources.dataservices.url=jdbc:h2:file:../h2/dataservices
# CONFIG: content-store using h2 file
spring.datasources.contentstore.url=jdbc:h2:file:../h2/contentstore

