
server.port=8088

# Camunda
camunda.bpm.admin-user.id=admin
camunda.bpm.admin-user.password=admin
camunda.bpm.deployment-resource-pattern=classpath*:/bpmn/*.bpmn

# Data Services client
mgmtp.a12.dataservices.client.configuration.base-url=http://localhost:8082/api

# UAA
mgmtp.a12.uaa.authentication.client.rest.uaa-base.url=http://localhost:8082/api
mgmtp.a12.uaa.authentication.client.rest.authentication-type=LOCAL
mgmtp.a12.uaa.authentication.client.rest.authentication-configuration.username=admin
mgmtp.a12.uaa.authentication.client.rest.authentication-configuration.password=A12PT-admintest
mgmtp.a12.uaa.authentication.types=LOCAL
mgmtp.a12.uaa.authentication.jwt.secret=bXlTZWNyZXRLZXkxMjM0NW15U2VjcmV0S2V5MTIzNDU=

mgmtp.a12.uaa.authentication.principal.access-rights-resource=file:../import/auth/roles.yaml
mgmtp.a12.uaa.authentication.principal.local-config.user-resources=file:../import/auth/users/*.yaml
mgmtp.a12.uaa.authentication.unsecured.urls=/${spring.jersey.application-path}/deployment,/${spring.jersey.application-path}/deployment/create,/${spring.jersey.application-path}/version,/${spring.jersey.application-path}/external-task/**

# Email
spring.mail.host=localhost
spring.mail.port=1025
spring.mail.username=no-reply@acme.org
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000
