camunda.bpm.client.base-url=http://localhost:8088/engine-rest
camunda.bpm.client.worker-id=generate-gift-card-worker
camunda.bpm.client.basic-auth.username=admin
camunda.bpm.client.basic-auth.password=admin
# Required: A12 date format used by A12 Workflows Engine
camunda.bpm.client.date-format=yyyy-MM-dd'T'HH:mm